-- Optional durable signal storage for Supabase.
-- Run this in Supabase SQL Editor.
create table if not exists public.trading_signals (
  id bigint generated by default as identity primary key,
  provider text not null,
  symbol text not null,
  direction text not null check (direction in ('BUY','SELL','NEUTRAL')),
  entry numeric,
  stop_loss numeric,
  take_profit numeric,
  timeframe text,
  message text,
  received_at timestamptz not null default now()
);
alter table public.trading_signals enable row level security;
-- Public read is optional. For a private dashboard, replace this policy with authenticated-user rules.
create policy "public read signals" on public.trading_signals for select using (true);
